name: Sync GitHub to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs -y
          git lfs install

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Add Hugging Face Remote
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          if git remote | grep -q hf; then
            echo "HF remote already exists"
          else
            git remote add hf https://Snehalkhalasi:$HF_TOKEN@huggingface.co/spaces/Snehalkhalasi/LLM1
          fi

      - name: Pull latest from HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git fetch hf
          git reset --hard hf/main || echo "No existing commits to reset"

      - name: Add and Commit All Files
        run: |
          git add .
          git commit -m "Sync GitHub repo to HF Space" || echo "No changes to commit"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push hf main --force
